### ISSUE TITLE
Missing header generation with compound security header.

### ISSUE THREAD

**Issue by wRLSS** [ErikWittern/openapi-snippet#104]
OpenAPI 3.0 supports usage of [multiple API Keys](https://swagger.io/docs/specification/authentication/api-keys/). 
```
components:
  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
    appId:
      type: apiKey
      in: header
      name: X-APP-ID
security:
  - apiKey: []
    appId:  []
```

However, X-APP-ID header is not properly appended to codesnippet during generation producing 
```
curl --request POST \
  --url https://petstore.com/api/v1/pet/ \
  --header 'X-API-Key: REPLACE_KEY_VALUE' \
  --header 'content-type: application/json' \
  --data '{}'
```
